---
#Project configuration
s2s_path: "S:\\"
#Files
httpx_ips: "http_from.{project_name}.ips.output.json"
httpx_domains: "http_from.{project_name}.domains.output.json"
domains_file: "domains.txt"
dpux_file: "dpux.txt"
unique_ip_ports_file: "unique_ip_ports.txt"
domains_cleaned_file: "domains_clean.txt"
